on:
  push:
    branches: [ master ]
  schedule:
    - cron: '30 3 * * 1'

env:
  CARGO_UNSTABLE_SPARSE_REGISTRY: true

name: build-caches
jobs:
  build-cache:
    name: build rust caches
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain: [1.60, stable, beta, nightly]
    steps:
      - uses: actions/checkout@v3

      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.toolchain }}

      - name: Rust Cache
        uses: Swatinem/rust-cache@v2
        with:
          prefix-key: 'rust'
          shared-key: 'cache'
      
      - name: Clean (prevent cache from getting large)
        run: cargo clean

      - name: Test (to build cache)
        run: cargo test --all-features