on:
  push:
    branches:
      - master

name: release-please
jobs:
  release-please:
    name: release-please
    runs-on: ubuntu-latest
    outputs:
        released: ${{ steps.release.outputs.releases_created }}
    steps:
      - uses: google-github-actions/release-please-action@v3
        id: release
        with:
          token: ${{ secrets.RELEASE_PLEASE_GITHUB_TOKEN }}
          release-type: rust
          package-name: simplify-polyline
          bump-minor-pre-major: true
