on:
  pull_request:
    branches: [ master ]

jobs:
  test_verify:
    name: test-and-verify-builds
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Rust Cache
        uses: Swatinem/rust-cache@v1.3.0
      - name: Test
        run: cargo test --features tests